apiVersion: apps/v1
kind: Deployment
metadata:
  name: yotta-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: yotta-web
  template:
    metadata:
      labels:
        app: yotta-web
    spec:
      nodeSelector:
        node-role.kubernetes.io/yotta-workload: "true"
      containers:
      - name: yotta-web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.targetPort }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.targetPort }}
